### ISSUE TITLE
CSS is clean and succinct

### ISSUE THREAD

**Issue by ad3429** [shoemann/prj-rev-bwfs-dasmoto#3]
https://github.com/shoemann/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/style.css#L5-L29

Your css is short, clean and succinct -- great job! One area of improvement here is the comment your main stylings so that when you come back to look at your code after a while, you remember exactly why you chose to style an element a particular way. Here is a quick refresher on commenting in CSS:

<img width="159" alt="css_comment" src="https://user-images.githubusercontent.com/25671399/28992428-47431a76-7969-11e7-8ca8-d67471a02ab8.png">

**Comment by shoemann** [comment]
Thank you,
Shoemann.
