### ISSUE TITLE
HTML is nicely organized/structured

### ISSUE THREAD

**Issue by ad3429** [shoemann/prj-rev-bwfs-dasmoto#4]
https://github.com/shoemann/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L8-L33

Your HTML is nicely organized/structured, and you generally followed excellent code practices. Make sure to keep it up!

**Comment by shoemann** [comment]
Thank you,
Shoemann.
