### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [shoemann/prj-rev-bwfs-dasmoto#5]
**Summary Grade: Satisfactory**

Good job! Your files are organized nicely, and you did a great job of following the client specification -- this is an important skill to have as a developer and you seem to understand that. Moreover, you generally followed excellent code practice, so make sure to keep that up!

I have made some comments in your code to take note of. First off, great job making use of classes and id's accordingly -- this is something that many learners seem to overlook so great job getting it right! Next off, make sure to comment the main parts of your code in future projects. This will greatly help you as your projects get larger and more complex. Here is a quick refresher on commenting in HTML and CSS, respectively:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/28992434-afb7acfc-7969-11e7-9dbe-40105c3c6dcb.png">

<img width="159" alt="css_comment" src="https://user-images.githubusercontent.com/25671399/28992435-b2678e7c-7969-11e7-8e9f-64adcb58310a.png">

Great job overall! As a further challenge, try using css to design your webpage even further! You did a great job in following the client specification, but for your own practice you should see how creative you can get by taking the design/styling of your site to the next level (for example, you can try experimenting with background colors on your other divs)

**Comment by shoemann** [comment]
Arton, 
Thank you very much for your time and kind words.
From now and on I will comment on my future projects and I will experiment with CSS a little bit more.
Thank you very much,
Shoemann.
